{{ $networkPolicies := .Values.networkPolicies.kafka }}
{{ if $networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kafka.fullname" . }}-egress-kafka
  namespace: {{ .Release.Namespace }}
{{- if .Values.additionalAnnotations }}
  annotations:
    {{ toYaml .Values.additionalAnnotations | nindent 4 }}
{{- end }}
  labels: {{ include "kafka.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- tpl (toYaml $networkPolicies.selectorLabels) . | nindent 6 }}
  egress:
    {{- tpl (toYaml $networkPolicies.egress) . | nindent 4 }}
{{ end }}
