apiVersion: v2
name: big-peer
description: A Helm chart for Kubernetes
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
home: https://docs.ditto.live/

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.14

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.39.2"
keywords:
  - ditto
  - bigpeer
sources:
  - https://github.com/getditto/ditto-helm
maintainers:
  - name: Ditto Live
    email: charts@ditto.live
dependencies:
  # Both longhorn and minio are used for storage, longhorn seems to be more robust
  - name: hades
    version: "1.39.2-4b6e4e"
    repository: "oci://quay.io/ditto-external"
    condition: hades.enabled
    tags:
      - hades
  - name: hydra-consul
    version: "0.1.0"
    repository: "oci://quay.io/ditto-external"
    condition: hydra-consul.enabled
    tags:
      - hydra-consul
  - name: hydra-store
    version: "1.39.2-4b6e4e"
    repository: "oci://quay.io/ditto-external"
    condition: hydra-store.enabled
    tags:
      - hydra-store
  - name: hydra-subscription
    version: "1.39.2-4b6e4e"
    repository: "oci://quay.io/ditto-external"
    condition: hydra-subscription.enabled
    tags:
      - hydra-subscription
  - name: service-token-validator
    version: "0.2.1"
    repository: "oci://quay.io/ditto-external"
    condition: service-token-validator.enabled
    tags:
      - service-token-validator
  - name: cert-manager
    version: "1.10.1"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled
    tags:
      - cert-manager
  - name: strimzi-kafka-operator
    version: "0.44.0"
    repository: "https://strimzi.io/charts"
    condition: strimzi-kafka-operator.enabled
    tags:
      - kafka-operator
  - name: kafka
    version: "0.3.5"
    repository: "https://getditto.github.io/helm-charts/"
    alias: kafka
    condition: kafka-cluster.enabled
    tags:
      - kafka
  - name: dummy-auth-webhook
    repository: "oci://quay.io/ditto-external"
    condition: dummy-auth-webhook.enabled
    version: "0.1.1"
    tags:
      - dummy-auth-webhook
  - name: live-query-resource-controller
    alias: live-query
    repository: "oci://quay.io/ditto-external"
    condition: live-query.enabled
    version: "0.1.0-002c59"
    tags:
      - live-query
  - name: kafka
    alias: live-query-kafka
    version: "0.3.5"
    repository: "https://getditto.github.io/helm-charts/"
    condition: live-query.enabled
    tags:
      - kafka
      - live-query
