name: chart-workflow

on:
  workflow_call:
  pull_request:

jobs:
  chart-testing:
    runs-on: [ubuntu-latest]
    container:
      image: quay.io/helmpack/chart-testing:v3.11.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: add repos
        run: |
          helm repo add cert-manager https://charts.jetstack.io
          helm repo add kafka https://strimzi.io/charts
          helm repo add ditto-helm-charts https://getditto.github.io/helm-charts/

      - name: Install dependencies
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run Helm Chart Testing
        run: |
          ct lint 2>&1 | tee chart-testing-output-ct-lint.txt

      - uses: mshick/add-pr-comment@v2
        with:
          preformatted: true
          message-id: "${{ github.event.number }}"
          message-path: chart-testing-output-*.txt
